"""Image-only pilot for scanner-specific RF1 no-harm gain selection.

This analysis reuses the locked RF1 outer-fold image audits.  For each FOV,
source scanner and evaluation fold, it selects between exact identity and the
13 frozen RF1 gain caps using only the other four folds.  A non-identity
candidate is eligible only when it passes the frozen gamut gate and does not
worsen target-spectrum log-RMSE in *every* selection fold.  PFM features and
downstream endpoints are neither loaded nor accepted as inputs.

This is a low-cost meta-cross-fit pilot, not a strict nested refit: each reused
outer-fold audit was generated by a gain fitted on that fold's complement.
Consequently, a selection-fold gain fit may have included the current
evaluation fold.  The script records this limitation explicitly and is meant
to decide whether a fully nested rerender is warranted.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd

from e5_comparator_population import FOVS, SCANNERS
from e5_reinhard_residual_frequency import (
    RF1_FOLDS,
    RF1_GAIN_CAP_CANDIDATES,
    RF1_VERSION,
    log_spectrum_rmse,
)


MATERIAL_MEAN_LIMIT = 0.005
MATERIAL_Q99_LIMIT = 0.05
PROJECTION_RGB_MAE_LIMIT = 0.002
FINAL_CLAMP_MAE_LIMIT = 1e-6
IDENTITY_CAP = 1.0
SPECTRUM_TOLERANCE = 1e-12


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fold-audit", default="outputs/e5_rf1_input_fold_audit")
    parser.add_argument(
        "--output", default="outputs/rf1_improvement_pilot/noharm"
    )
    parser.add_argument("--dpi", type=int, default=220)
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def gamut_gate(
    material: np.ndarray,
    projection_rgb_mae: np.ndarray,
    final_clamp_mae: np.ndarray,
) -> bool:
    """Apply the frozen RF1 input-only gamut thresholds to patch metrics."""
    material = np.asarray(material, dtype=np.float64).reshape(-1)
    projection_rgb_mae = np.asarray(projection_rgb_mae, dtype=np.float64).reshape(-1)
    final_clamp_mae = np.asarray(final_clamp_mae, dtype=np.float64).reshape(-1)
    if not material.size or not (
        np.isfinite(material).all()
        and np.isfinite(projection_rgb_mae).all()
        and np.isfinite(final_clamp_mae).all()
    ):
        return False
    return bool(
        material.mean() <= MATERIAL_MEAN_LIMIT
        and np.quantile(material, 0.99) <= MATERIAL_Q99_LIMIT
        and projection_rgb_mae.mean() <= PROJECTION_RGB_MAE_LIMIT
        and final_clamp_mae.max() <= FINAL_CLAMP_MAE_LIMIT
    )


def choose_candidate(
    candidate_caps: np.ndarray,
    fold_base_rmse: np.ndarray,
    fold_candidate_rmse: np.ndarray,
    fold_gamut_pass: np.ndarray,
    pooled_candidate_rmse: np.ndarray,
    tolerance: float = SPECTRUM_TOLERANCE,
) -> tuple[int, np.ndarray]:
    """Choose the best candidate after a conservative cross-fold no-harm gate.

    Candidate zero must be exact identity.  It is still checked rather than
    silently forced eligible so malformed synthetic/test inputs fail loudly.
    Ties resolve toward the weaker (smaller-cap) candidate.
    """
    caps = np.asarray(candidate_caps, dtype=np.float64)
    base = np.asarray(fold_base_rmse, dtype=np.float64)
    candidate = np.asarray(fold_candidate_rmse, dtype=np.float64)
    gamut = np.asarray(fold_gamut_pass, dtype=bool)
    pooled = np.asarray(pooled_candidate_rmse, dtype=np.float64)
    if (
        caps.ndim != 1
        or len(caps) == 0
        or not np.isclose(caps[0], IDENTITY_CAP)
        or base.ndim != 1
        or candidate.shape != (len(base), len(caps))
        or gamut.shape != candidate.shape
        or pooled.shape != caps.shape
        or not np.isfinite(caps).all()
        or not np.isfinite(base).all()
        or not np.isfinite(candidate).all()
        or not np.isfinite(pooled).all()
    ):
        raise ValueError("invalid no-harm candidate arrays")
    nonworse = np.all(candidate <= base[:, None] + float(tolerance), axis=0)
    eligible = np.all(gamut, axis=0) & nonworse
    if not eligible[0]:
        raise RuntimeError("exact identity must pass the no-harm gate")
    eligible_indices = np.flatnonzero(eligible)
    # np.argmin is stable, and caps are strictly ascending, so exact ties favor
    # the weakest correction.
    selected = int(eligible_indices[np.argmin(pooled[eligible_indices])])
    return selected, eligible


def choose_candidate_one_se(
    candidate_caps: np.ndarray,
    fold_base_rmse: np.ndarray,
    fold_candidate_rmse: np.ndarray,
    fold_gamut_pass: np.ndarray,
    tolerance: float = SPECTRUM_TOLERANCE,
) -> tuple[int, np.ndarray, np.ndarray, int, float, float, np.ndarray]:
    """Select the weakest eligible candidate within one SE of the best.

    Fold-wise delta is candidate RMSE minus identity/base RMSE.  Eligibility
    requires frozen gamut safety and non-worsening in every inner fold.  The SE
    is the sample SD (ddof=1) of the best candidate's fold deltas divided by
    sqrt(number of folds).  Exact ties favor identity/the smaller cap.
    """
    caps = np.asarray(candidate_caps, dtype=np.float64)
    base = np.asarray(fold_base_rmse, dtype=np.float64)
    candidate = np.asarray(fold_candidate_rmse, dtype=np.float64)
    gamut = np.asarray(fold_gamut_pass, dtype=bool)
    if (
        caps.ndim != 1
        or len(caps) == 0
        or not np.isclose(caps[0], IDENTITY_CAP)
        or np.any(np.diff(caps) <= 0)
        or base.ndim != 1
        or len(base) < 2
        or candidate.shape != (len(base), len(caps))
        or gamut.shape != candidate.shape
        or not np.isfinite(caps).all()
        or not np.isfinite(base).all()
        or not np.isfinite(candidate).all()
    ):
        raise ValueError("invalid one-SE candidate arrays")
    delta = candidate - base[:, None]
    mean_delta = delta.mean(axis=0)
    nonworse = np.all(delta <= float(tolerance), axis=0)
    eligible = np.all(gamut, axis=0) & nonworse
    if not eligible[0]:
        raise RuntimeError("exact identity must pass the one-SE no-harm gate")
    eligible_indices = np.flatnonzero(eligible)
    best = int(eligible_indices[np.argmin(mean_delta[eligible_indices])])
    best_se = float(delta[:, best].std(ddof=1) / np.sqrt(len(base)))
    threshold = float(mean_delta[best] + best_se)
    within_one_se = eligible & (mean_delta <= threshold + float(tolerance))
    selected = int(np.flatnonzero(within_one_se)[0])
    return selected, eligible, mean_delta, best, best_se, threshold, within_one_se


def candidate_power(fold: dict[str, np.ndarray], candidate_index: int, scanner_index: int):
    if candidate_index == 0:
        return fold["validation_base_power"][scanner_index]
    return fold["validation_output_power"][candidate_index - 1, scanner_index]


def candidate_metrics(
    fold: dict[str, np.ndarray], candidate_index: int, scanner_index: int
) -> dict[str, np.ndarray]:
    patch_count = len(fold["heldout_slide_ids"]) * 100
    if candidate_index == 0:
        zero = np.zeros(patch_count, dtype=np.float64)
        return {
            "material_range_fraction": zero,
            "projection_fraction": zero,
            "projection_rgb_mae": zero,
            "final_clamp_mae": zero,
        }
    source_index = candidate_index - 1
    return {
        name: fold[name][source_index, :, scanner_index].reshape(-1)
        for name in (
            "material_range_fraction",
            "projection_fraction",
            "projection_rgb_mae",
            "final_clamp_mae",
        )
    }


def load_fold(path: Path) -> tuple[dict[str, np.ndarray], dict]:
    summary_path = path.with_suffix(".summary.json")
    if not path.exists() or not summary_path.exists():
        raise FileNotFoundError(path)
    summary = json.loads(summary_path.read_text())
    if not (
        summary.get("analysis") == "e5_rf1_input_fold_audit"
        and summary.get("rf1_version") == RF1_VERSION
        and summary.get("outcome_access") is False
        and summary.get("output_sha256") == sha256(path)
        and summary.get("input_fold_gate_pass") is True
    ):
        raise RuntimeError(f"invalid cross-fitted RF1 input audit: {path}")
    with np.load(path) as source:
        fold = {name: source[name] for name in source.files}
    caps = np.asarray(RF1_GAIN_CAP_CANDIDATES, dtype=np.float64)
    expected_shape = (len(caps), len(fold["heldout_slide_ids"]), len(SCANNERS) - 1, 100)
    if (
        not np.array_equal(fold["caps"], caps)
        or fold["validation_output_power"].shape
        != (len(caps), len(SCANNERS) - 1, len(fold["validation_target_power"]))
        or fold["material_range_fraction"].shape != expected_shape
        or np.any(fold["validation_target_power"] < 0)
        or np.any(fold["validation_base_power"] < 0)
        or np.any(fold["validation_output_power"] < 0)
    ):
        raise RuntimeError(f"invalid RF1 audit arrays: {path}")
    return fold, summary


def render_figure(
    cell: pd.DataFrame,
    output: Path,
    dpi: int,
    stem: str = "rf1_noharm_spectrum_pilot",
    method_label: str = "Cross-fit no-harm selection",
):
    import matplotlib.pyplot as plt

    def compact_counts(text: str) -> str:
        values = text.split(",")
        ordered = list(dict.fromkeys(values))
        return "; ".join(
            f"{'I' if value == '1' else value}×{values.count(value)}"
            for value in ordered
        )

    colors = {"original": "#9CA3AF", "noharm": "#2563EB"}
    scanners = list(SCANNERS[1:])
    figure, axes = plt.subplots(1, len(FOVS), figsize=(15.5, 4.5), sharey=True)
    x = np.arange(len(scanners), dtype=float)
    for axis, fov in zip(axes, FOVS):
        local = cell[cell["fov"] == fov].set_index("scanner").loc[scanners]
        width = 0.36
        axis.bar(
            x - width / 2,
            local["original_cap_1p25_rmse_reduction_percent"],
            width,
            color=colors["original"],
            label="Original panel-wide cap 1.25",
        )
        axis.bar(
            x + width / 2,
            local["noharm_rmse_reduction_percent"],
            width,
            color=colors["noharm"],
            label=method_label,
        )
        axis.axhline(0.0, color="#111827", linewidth=0.8)
        tick_labels = [
            f"{scanner.upper()}\n{compact_counts(row.selected_caps)}"
            for scanner, row in zip(scanners, local.itertuples())
        ]
        axis.set_xticks(x, tick_labels)
        axis.set_title(f"FOV {fov}px")
        axis.grid(axis="y", color="#E5E7EB", linewidth=0.7)
    axes[0].set_ylabel("Target-spectrum log-RMSE reduction (%)")
    axes[1].legend(loc="upper right", frameon=False, fontsize=8)
    figure.text(
        0.5,
        -0.02,
        "Second tick line summarizes five evaluation-fold choices (I = exact identity). "
        "Selection uses image spectrum + gamut only; PFM endpoints are not accessed.",
        ha="center",
        fontsize=8,
    )
    figure.tight_layout(rect=(0, 0.07, 1, 0.99))
    paths = []
    for suffix in ("png", "pdf"):
        path = output / f"{stem}.{suffix}"
        figure.savefig(path, dpi=dpi, bbox_inches="tight")
        paths.append(path)
    plt.close(figure)
    return paths


def format_selection(values: list[float]) -> str:
    return "/".join("I" if np.isclose(value, IDENTITY_CAP) else f"{value:g}" for value in values)


def main():
    args = parse_args()
    audit_root = Path(args.fold_audit)
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    candidate_caps = np.asarray(
        [IDENTITY_CAP, *RF1_GAIN_CAP_CANDIDATES], dtype=np.float64
    )

    folds: dict[tuple[int, int], dict[str, np.ndarray]] = {}
    source_hashes = {}
    for fov in FOVS:
        for fold_index in range(RF1_FOLDS):
            path = audit_root / f"fov_{fov}_fold_{fold_index}.npz"
            values, summary = load_fold(path)
            if int(values["fov"]) != fov or int(values["fold"]) != fold_index:
                raise RuntimeError(f"RF1 fold identity mismatch: {path}")
            folds[fov, fold_index] = values
            source_hashes[f"fov_{fov}_fold_{fold_index}"] = summary["output_sha256"]

    selection_rows = []
    evaluation_rows = []
    cell_rows = []
    selected_by_cell: dict[tuple[int, str], list[int]] = {}

    for fov in FOVS:
        frequency = np.asarray(folds[fov, 0]["validation_target_power"])
        # The radial frequency grid is reproducible from FOV and stored in the
        # matching fold-statistics file, but log-RMSE needs its values.  Load it
        # from the audited statistics referenced by the fold summary sibling.
        statistics_path = Path("outputs/e5_rf1_fold_statistics") / f"fov_{fov}_fold_0.npz"
        if not statistics_path.exists():
            raise FileNotFoundError(statistics_path)
        with np.load(statistics_path) as source:
            radial_frequency = np.asarray(source["radial_frequency"], dtype=np.float64)
        if frequency.shape != radial_frequency.shape:
            raise RuntimeError(f"FOV {fov}: inconsistent frequency shape")

        for scanner_index, scanner in enumerate(SCANNERS[1:]):
            selected_indices = []
            selected_output_powers = []
            selected_metric_sets = []
            target_powers = []
            base_powers = []
            original_powers = []
            for evaluation_fold in range(RF1_FOLDS):
                selection_folds = [
                    fold for fold in range(RF1_FOLDS) if fold != evaluation_fold
                ]
                base_rmse = []
                candidate_rmse = []
                gamut_pass = []
                for selection_fold in selection_folds:
                    values = folds[fov, selection_fold]
                    target = values["validation_target_power"]
                    base = values["validation_base_power"][scanner_index]
                    base_rmse.append(log_spectrum_rmse(base, target, radial_frequency))
                    local_rmse = []
                    local_gamut = []
                    for candidate_index in range(len(candidate_caps)):
                        power = candidate_power(values, candidate_index, scanner_index)
                        metrics = candidate_metrics(values, candidate_index, scanner_index)
                        local_rmse.append(
                            log_spectrum_rmse(power, target, radial_frequency)
                        )
                        local_gamut.append(
                            gamut_gate(
                                metrics["material_range_fraction"],
                                metrics["projection_rgb_mae"],
                                metrics["final_clamp_mae"],
                            )
                        )
                    candidate_rmse.append(local_rmse)
                    gamut_pass.append(local_gamut)

                pooled_target = sum(
                    folds[fov, fold]["validation_target_power"]
                    for fold in selection_folds
                )
                pooled_candidate_rmse = np.asarray(
                    [
                        log_spectrum_rmse(
                            sum(
                                candidate_power(folds[fov, fold], index, scanner_index)
                                for fold in selection_folds
                            ),
                            pooled_target,
                            radial_frequency,
                        )
                        for index in range(len(candidate_caps))
                    ]
                )
                base_rmse = np.asarray(base_rmse)
                candidate_rmse = np.asarray(candidate_rmse)
                gamut_pass = np.asarray(gamut_pass)
                selected, eligible = choose_candidate(
                    candidate_caps,
                    base_rmse,
                    candidate_rmse,
                    gamut_pass,
                    pooled_candidate_rmse,
                )
                selected_indices.append(selected)

                pooled_base_rmse = log_spectrum_rmse(
                    sum(
                        folds[fov, fold]["validation_base_power"][scanner_index]
                        for fold in selection_folds
                    ),
                    pooled_target,
                    radial_frequency,
                )
                for candidate_index, cap in enumerate(candidate_caps):
                    selection_rows.append(
                        {
                            "fov": fov,
                            "scanner": scanner,
                            "evaluation_fold": evaluation_fold,
                            "candidate": "identity"
                            if candidate_index == 0
                            else f"cap_{cap:g}",
                            "gain_cap": cap,
                            "selection_folds": ",".join(map(str, selection_folds)),
                            "selection_pooled_base_rmse": pooled_base_rmse,
                            "selection_pooled_output_rmse": pooled_candidate_rmse[
                                candidate_index
                            ],
                            "selection_rmse_change": pooled_candidate_rmse[candidate_index]
                            - pooled_base_rmse,
                            "all_selection_folds_gamut_pass": bool(
                                gamut_pass[:, candidate_index].all()
                            ),
                            "all_selection_folds_spectrum_nonworse": bool(
                                np.all(
                                    candidate_rmse[:, candidate_index]
                                    <= base_rmse + SPECTRUM_TOLERANCE
                                )
                            ),
                            "eligible": bool(eligible[candidate_index]),
                            "selected": candidate_index == selected,
                        }
                    )

                values = folds[fov, evaluation_fold]
                target = values["validation_target_power"]
                base = values["validation_base_power"][scanner_index]
                selected_power = candidate_power(values, selected, scanner_index)
                selected_metrics = candidate_metrics(values, selected, scanner_index)
                before = log_spectrum_rmse(base, target, radial_frequency)
                after = log_spectrum_rmse(selected_power, target, radial_frequency)
                evaluation_rows.append(
                    {
                        "fov": fov,
                        "scanner": scanner,
                        "evaluation_fold": evaluation_fold,
                        "heldout_slides": len(values["heldout_slide_ids"]),
                        "selected_candidate": "identity"
                        if selected == 0
                        else f"cap_{candidate_caps[selected]:g}",
                        "selected_gain_cap": candidate_caps[selected],
                        "base_log_spectrum_rmse": before,
                        "output_log_spectrum_rmse": after,
                        "log_spectrum_rmse_change": after - before,
                        "rmse_reduction_percent": 100.0 * (before - after) / before,
                        "evaluation_spectrum_nonworse": after
                        <= before + SPECTRUM_TOLERANCE,
                        "evaluation_gamut_pass": gamut_gate(
                            selected_metrics["material_range_fraction"],
                            selected_metrics["projection_rgb_mae"],
                            selected_metrics["final_clamp_mae"],
                        ),
                    }
                )
                selected_output_powers.append(selected_power)
                selected_metric_sets.append(selected_metrics)
                target_powers.append(target)
                base_powers.append(base)
                original_powers.append(
                    values["validation_output_power"][
                        list(RF1_GAIN_CAP_CANDIDATES).index(1.25), scanner_index
                    ]
                )

            selected_by_cell[fov, scanner] = selected_indices
            pooled_target = sum(target_powers)
            pooled_base = sum(base_powers)
            pooled_noharm = sum(selected_output_powers)
            pooled_original = sum(original_powers)
            before = log_spectrum_rmse(pooled_base, pooled_target, radial_frequency)
            after = log_spectrum_rmse(pooled_noharm, pooled_target, radial_frequency)
            original_after = log_spectrum_rmse(
                pooled_original, pooled_target, radial_frequency
            )
            material = np.concatenate(
                [value["material_range_fraction"] for value in selected_metric_sets]
            )
            projection = np.concatenate(
                [value["projection_fraction"] for value in selected_metric_sets]
            )
            projection_mae = np.concatenate(
                [value["projection_rgb_mae"] for value in selected_metric_sets]
            )
            final_mae = np.concatenate(
                [value["final_clamp_mae"] for value in selected_metric_sets]
            )
            selected_caps = [float(candidate_caps[index]) for index in selected_indices]
            cell_rows.append(
                {
                    "fov": fov,
                    "scanner": scanner,
                    "patches": len(material),
                    "selection_label": format_selection(selected_caps),
                    "selected_identity_folds": sum(
                        np.isclose(value, IDENTITY_CAP) for value in selected_caps
                    ),
                    "selected_caps": ",".join(f"{value:g}" for value in selected_caps),
                    "base_log_spectrum_rmse": before,
                    "noharm_output_log_spectrum_rmse": after,
                    "noharm_log_spectrum_rmse_change": after - before,
                    "noharm_rmse_reduction_percent": 100.0 * (before - after) / before,
                    "original_cap_1p25_output_log_spectrum_rmse": original_after,
                    "original_cap_1p25_log_spectrum_rmse_change": original_after - before,
                    "original_cap_1p25_rmse_reduction_percent": 100.0
                    * (before - original_after)
                    / before,
                    "noharm_minus_original_output_rmse": after - original_after,
                    "material_range_fraction_mean": float(material.mean()),
                    "material_range_fraction_q99": float(np.quantile(material, 0.99)),
                    "projection_fraction_mean": float(projection.mean()),
                    "projection_rgb_mae_mean": float(projection_mae.mean()),
                    "final_clamp_mae_max": float(final_mae.max()),
                    "aggregate_spectrum_nonworse": after
                    <= before + SPECTRUM_TOLERANCE,
                    "aggregate_gamut_pass": gamut_gate(
                        material, projection_mae, final_mae
                    ),
                }
            )

    selection = pd.DataFrame(selection_rows)
    evaluation = pd.DataFrame(evaluation_rows)
    cell = pd.DataFrame(cell_rows)
    if not (
        len(selection) == len(FOVS) * (len(SCANNERS) - 1) * RF1_FOLDS * len(candidate_caps)
        and len(evaluation) == len(FOVS) * (len(SCANNERS) - 1) * RF1_FOLDS
        and len(cell) == len(FOVS) * (len(SCANNERS) - 1)
        and np.isfinite(
            cell.select_dtypes(include=[np.number]).to_numpy(dtype=np.float64)
        ).all()
    ):
        raise RuntimeError("incomplete no-harm pilot population")

    selection_path = output / "candidate_selection.csv"
    evaluation_path = output / "heldout_fold_evaluation.csv"
    cell_path = output / "scanner_fov_summary.csv"
    selection.to_csv(selection_path, index=False)
    evaluation.to_csv(evaluation_path, index=False)
    cell.to_csv(cell_path, index=False)
    figure_paths = render_figure(cell, output, args.dpi)

    identity_selections = int(
        np.isclose(evaluation["selected_gain_cap"], IDENTITY_CAP).sum()
    )
    summary = {
        "analysis": "rf1_scanner_specific_noharm_gain_pilot",
        "parent_rf1_version": RF1_VERSION,
        "outcome_access": False,
        "pfm_feature_access": False,
        "selection_unit": "FOV x source scanner x evaluation fold",
        "selection_protocol": (
            "leave-one-fold-out meta-selection over locked cross-fitted RF1 image audits; "
            "identity plus frozen caps; candidate must pass gamut and be spectrum-nonworse "
            "in every selection fold; minimize pooled selection spectrum RMSE"
        ),
        "strict_nested_training_exclusion": False,
        "strict_nested_limitation": (
            "Each reused selection-fold transform was fitted on that fold's complement, "
            "which can include the current evaluation fold. A full nested rerender is "
            "required for confirmatory performance estimation."
        ),
        "fovs": list(FOVS),
        "source_scanners": list(SCANNERS[1:]),
        "folds": RF1_FOLDS,
        "candidate_caps": candidate_caps.tolist(),
        "selection_cells": len(evaluation),
        "aggregate_cells": len(cell),
        "identity_selections": identity_selections,
        "nonidentity_selections": int(len(evaluation) - identity_selections),
        "heldout_fold_spectrum_nonworse": int(
            evaluation["evaluation_spectrum_nonworse"].sum()
        ),
        "heldout_fold_spectrum_total": len(evaluation),
        "aggregate_spectrum_nonworse_cells": int(
            cell["aggregate_spectrum_nonworse"].sum()
        ),
        "aggregate_gamut_pass_cells": int(cell["aggregate_gamut_pass"].sum()),
        "original_cap_1p25_spectrum_nonworse_cells": int(
            (cell["original_cap_1p25_log_spectrum_rmse_change"] <= 0).sum()
        ),
        "mean_noharm_rmse_reduction_percent": float(
            cell["noharm_rmse_reduction_percent"].mean()
        ),
        "mean_original_cap_1p25_rmse_reduction_percent": float(
            cell["original_cap_1p25_rmse_reduction_percent"].mean()
        ),
        "s360_identity_selections": int(
            np.isclose(
                evaluation.loc[evaluation["scanner"] == "s360", "selected_gain_cap"],
                IDENTITY_CAP,
            ).sum()
        ),
        "s360_selections": int((evaluation["scanner"] == "s360").sum()),
        "source_fold_audit_sha256": source_hashes,
        "artifacts": {
            str(path.name): sha256(path)
            for path in [selection_path, evaluation_path, cell_path, *figure_paths]
        },
        "pilot_gate_pass": bool(
            len(cell) == 15
            and cell["aggregate_gamut_pass"].all()
            and cell["aggregate_spectrum_nonworse"].all()
            and evaluation["evaluation_gamut_pass"].all()
            and evaluation["evaluation_spectrum_nonworse"].all()
            and identity_selections > 0
        ),
    }
    summary_path = output / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))
    if not summary["pilot_gate_pass"]:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
